# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'
require 'exchange_file_importer'

Rails.application.load_tasks

namespace :exchange do
  desc 'import NASDAQ, NYSE, AMEX exchange data'
  task :import_all => :environment do
    exchange_data = {
      "NASDAQ" => "lib/seeds/NASDAQ.csv",
      "NYSE"   => "lib/seeds/NYSE.csv",
      "AMEX"   => "lib/seeds/AMEX.csv",
    }

    exchange_data.each do | name, path |
      ExchangeFileImporter.import(exchange_name: name, file_path: path)
    end
  end
end
